import Header from '@/components/Header';
import CTAButton from '@/components/CTAButton';
import CTAForm from '@/components/CTAForm';

const benefits = ['Understand what to expect during the consultation', 'Know what information you should prepare', 'Create your customized AI marketing plan', 'Get the most value from the call'];
const steps = [['01', 'Share your information', 'Tell us about your business and biggest marketing challenge.'], ['02', 'One-to-One Consultation', 'Book a free AI marketing consultation call.'], ['03', 'Get your customized plan', 'Create a customized AI marketing plan for your business.']];

export default function Home() {
  return <main><Header /><section className="mesh grid-pattern px-5 pb-20 pt-14 text-center sm:pb-28 sm:pt-20"><div className="mx-auto max-w-4xl"><p className="eyebrow">Free AI marketing consultation</p><h1 className="display mx-auto mt-5 max-w-4xl text-5xl font-black leading-[.98] sm:text-7xl">Get a <span className="text-red-600">Free</span> <span className="text-brand-600">customized</span> digital marketing plan for your business.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-600">A free AI marketing consultation call for small and medium business owners who want to sell their products or services using digital marketing and AI.</p><div className="mt-9"><CTAButton /></div></div></section>
    <section className="px-5 py-20 sm:py-28"><div className="mx-auto max-w-3xl"><p className="eyebrow text-center">How you benefit from this consultation</p><h2 className="display mt-4 text-center text-4xl font-black sm:text-5xl">A clearer next step for your business.</h2><ul className="mx-auto mt-10 grid max-w-2xl gap-4 sm:grid-cols-2">{benefits.map((item) => <li key={item} className="flex gap-3 rounded-2xl border border-green-900/10 bg-white p-5 text-base leading-6 shadow-sm"><span className="mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-100 text-xs font-black text-brand-700">✓</span>{item}</li>)}</ul></div></section>
    <section className="bg-white px-5 py-20 sm:py-28"><div className="mx-auto max-w-5xl"><p className="eyebrow text-center">Consultation process</p><h2 className="display mt-4 text-center text-4xl font-black sm:text-5xl">Three simple steps.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([number, title, body]) => <div key={number} className="rounded-3xl border border-green-900/10 bg-brand-50 p-7"><span className="text-sm font-black text-brand-600">{number}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{body}</p></div>)}</div></div></section>
    <section className="px-5 py-20 sm:py-28" id="booking"><div className="mx-auto grid max-w-5xl gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><div className="lg:sticky lg:top-8"><p className="eyebrow">Book the call</p><h2 className="display mt-4 text-4xl font-black sm:text-5xl">One-to-One Consultation</h2><p className="mt-5 text-lg leading-8 text-slate-600">Customized Strategy for Your Business.</p><p className="mt-8 rounded-2xl bg-brand-100 p-5 font-semibold leading-7 text-brand-700">Book your free AI marketing consultation call and create your customized digital marketing plan.</p></div><CTAForm /></div></section>
  </main>;
}
